version: 2

sources:
  - name: MR
    config: 
      enabled: true
    database: course15secondday
    tables:
      - name: hit_98_2020
      - name: song_w_genres
      - name: top_chart_200
      - name: tophits_2000_2019
      - name: track_chart_2014_2022
      - name: spotify_track_dataset

  - name: MR_Popular_Features
    config: 
      enabled: true
    database: course15secondday
    tables:
      - name: popular_features
      - name: popular_predict_song
      - name: popular_song_1921_2020
      - name: unpopular_songs

